[package]
name = "stream-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "stream_core"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
url = { workspace = true }
log = { workspace = true }
