[package]
name = "relay"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "relay"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
futures-util = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tokio-rustls = "0.26"
rustls-pemfile = "2"
