[package]
name = "desktop"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "test-client"
path = "src/bin/test_client.rs"

[dependencies]
stream-core = { path = "../core" }
tokio = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
